### ISSUE TITLE
Switchable Employee files field (grid / list view)

### ISSUE THREAD

**Issue by franzegos** [TempName-1/rdi-payroll-system#125]
Create 2 types of view in employee files 

![Switchable Employee files view.PNG](https://images.zenhubusercontent.com/616fad0c18fb23251f970759/59f8f6d3-5c0e-469c-9b19-29519e48e22f)

![Grid view.PNG](https://images.zenhubusercontent.com/616fad0c18fb23251f970759/af3dfcb4-9b65-40b6-b327-1612d4ed733c)

**Comment by CloudyMushroom** [comment]
@glendell03 pre fix na yung sidebar, mababalik mo ba ulit? yung content pero using component na nagawa ko? yung folder component? naka push naman na sa feat/auditor-employee-files.

![image.png](https://images.zenhubusercontent.com/616ff89477f44fa9f2d93603/6524acd1-767a-43f1-9f22-802cb4280676)
