### ISSUE TITLE
Sidebar not fixed / filter must have scroll overflow

### ISSUE THREAD

**Issue by franzegos** [TempName-1/rdi-payroll-system#167]
![image.png](https://images.zenhubusercontent.com/616fad0c18fb23251f970759/49915b97-2a07-498c-ad1d-0148784a9d64)

Filters, Sort, Search employee header and reset selection footer must be fixed.

https://www.figma.com/proto/9VNCJzBiJhHqK2c61sEaxx/RDI-Payroll-System?node-id=1477%3A1688&scaling=scale-down-width&page-id=302%3A172&starting-point-node-id=796%3A1992&show-proto-sidebar=1

**Comment by glendell03** [comment]
sira parin siya?

**Comment by franzegos** [comment]
> sira parin siya?

diba feat/menu to sir? okay na syaaaa
